import { ShieldCheck, Scale, Network } from "lucide-react";
import Image from "next/image";
import { PageIntro } from "@/components/PageIntro";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";

export const metadata = { title: "About Edulage", description: "Learn about Edulage's enabling-not-replacing position and governance model." };
export default function AboutPage() {
  return <><PageIntro eyebrow="The platform" title="Education infrastructure built around institutional trust." description="Edulage is a marketplace and infrastructure layer for accredited higher-education institutions, learners, and the places that connect them." /><section className="group relative h-72 overflow-hidden bg-navy-900"><Image src="/media/study-online.jpg" alt="Learner studying online" fill sizes="100vw" className="image-zoom object-cover" /><div className="hero-media-overlay absolute inset-0" /><Container><div className="relative flex h-72 items-end pb-8 text-white"><p className="max-w-2xl text-2xl font-bold">Make quality education easier to find, reach, and trust.</p></div></Container></section><Section title="Enabling, not replacing"><div className="grid gap-10 md:grid-cols-2"><div><p className="text-lg leading-8 text-ink-600">Institutions remain the source of academic authority. Edulage makes programmes discoverable, supports access through Open Education Centers, and provides shared tools for digital delivery.</p><p className="mt-5 leading-7 text-ink-600">Edulage does not admit students, approve curricula, teach on behalf of institutions, or issue credentials. Those responsibilities stay with the institutions.</p></div><div className="grid gap-3">{[[ShieldCheck, "Trust", "Standards and transparent institutional responsibility guide participation."], [Scale, "Sovereignty", "Academic decisions remain with faculty and institutional governance."], [Network, "Access", "A shared network makes quality education easier to find and reach."]].map(([Icon, title, text]) => <div key={title as string} className="card-hover flex gap-4 rounded-xl border border-line p-5"><Icon className="shrink-0 text-teal-600" size={24} /><div><h2 className="font-bold text-navy-800">{title as string}</h2><p className="mt-1 text-sm leading-6 text-ink-600">{text as string}</p></div></div>)}</div></div></Section><section className="relative overflow-hidden bg-surface py-20"><Container><div className="grid gap-10 md:grid-cols-[1fr_0.8fr] md:items-center"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-600">Governance model</p><h2 className="mt-3 text-3xl font-bold text-navy-800">Clear roles, accountable outcomes</h2><p className="mt-5 leading-7 text-ink-600">Participating institutions are responsible for academic quality, admissions, learner records, assessment, and credentials. Center operators are responsible for reliable facilities and secure examinations. Edulage maintains the marketplace, shared standards, and verification infrastructure.</p></div><div className="group relative h-64 overflow-hidden rounded-xl"><Image src="/media/graduation.jpg" alt="Graduates celebrating academic achievement" fill sizes="(max-width: 767px) 100vw, 40vw" className="image-zoom object-cover" /></div></div></Container></section></>;
}
