import { ShieldCheck, Scale, Network } from "lucide-react";
import { PageIntro } from "@/components/PageIntro";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";

export const metadata = { title: "About Edulage", description: "Learn about Edulage's enabling-not-replacing position and governance model." };
export default function AboutPage() {
  return <><PageIntro eyebrow="The platform" title="Education infrastructure built around institutional trust." description="Edulage is a marketplace and infrastructure layer for accredited higher-education institutions, learners, and the places that connect them." /><Section title="Enabling, not replacing"><div className="grid gap-10 md:grid-cols-2"><div><p className="text-lg leading-8 text-ink-600">Institutions remain the source of academic authority. Edulage makes programmes discoverable, supports access through Open Education Centers, and provides shared tools for digital delivery.</p><p className="mt-5 leading-7 text-ink-600">Edulage does not admit students, approve curricula, teach on behalf of institutions, or issue credentials. Those responsibilities stay with the institutions.</p></div><div className="grid gap-3">{[[ShieldCheck, "Trust", "Standards and transparent institutional responsibility guide participation."], [Scale, "Sovereignty", "Academic decisions remain with faculty and institutional governance."], [Network, "Access", "A shared network makes quality education easier to find and reach."]].map(([Icon, title, text]) => <div key={title as string} className="flex gap-4 rounded-lg border border-line p-5"><Icon className="shrink-0 text-teal-600" size={24} /><div><h2 className="font-bold text-navy-800">{title as string}</h2><p className="mt-1 text-sm leading-6 text-ink-600">{text as string}</p></div></div>)}</div></div></Section><section className="bg-surface py-20"><Container><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-600">Governance model</p><h2 className="mt-3 text-3xl font-bold text-navy-800">Clear roles, accountable outcomes</h2><p className="mt-5 leading-7 text-ink-600">Participating institutions are responsible for academic quality, admissions, learner records, assessment, and credentials. Center operators are responsible for reliable facilities and secure examinations. Edulage maintains the marketplace, shared standards, and verification infrastructure.</p></div></Container></section></>;
}
