import { PolicyPage } from "@/components/PolicyPage";
export const metadata = { title: "Refunds and payments", description: "How payments, receipts and refunds work for paid programmes on EduLage." };
export default function Page() {
  return <PolicyPage eyebrow="Legal" title="Refunds and payments" updated="7 October 2026" contact="billing@edulage.org" description="What you pay, when you pay it, how you get a receipt and when a payment can be refunded." sections={[
    { title: "What you pay", body: "The fee for a paid course or programme is shown on the programme page and again before you confirm payment. Fees are set by the institution. Unless stated otherwise they are in Nigerian naira (₦) and include applicable taxes. Application, examination or supervised-assessment fees, where an institution charges them, are listed separately." },
    { title: "How you pay", body: "Payments are processed securely by Paystack by card, bank transfer, USSD or mobile money. EduLage never sees or stores your full card details. Your enrolment is activated as soon as the payment is confirmed — usually within seconds." },
    { title: "Receipts", body: "A receipt is e-mailed to you after every successful payment and is available at any time in My learning → Payments. It shows the programme, institution, amount, payment reference and date. Institutions can also issue their own invoices on request." },
    { title: "When a refund is available", body: "You can request a full refund of a course fee if:", points: ["You request it within 14 days of payment, and", "You have not yet accessed graded assessments or completed more than 10% of the course, and", "No certificate has been issued"] },
    { title: "When a refund is not available", body: "Refunds are not normally available after the 14-day period, once you have substantially started the course, after a certificate has been issued, or for application and examination fees that have already been processed by the institution. Degree and other admission-based programmes follow the awarding institution's published refund schedule, which may differ from the rules above." },
    { title: "Cancelled or changed programmes", body: "If an institution cancels a course run before it starts, or changes its start date by more than 30 days, you are entitled to a full refund or a free transfer to another run, whichever you prefer." },
    { title: "How to request a refund", body: "E-mail billing@edulage.org from your registered address with the payment reference from your receipt, or use the contact form with the topic “Payments and receipts”. We confirm receipt within two working days. Approved refunds are returned to the original payment method within 5–10 working days depending on your bank." },
    { title: "Disputes", body: "If you disagree with a refund decision, ask for it to be reviewed; a different member of the team will reconsider it within ten working days. Nothing in this policy limits your statutory consumer rights." },
  ]} />;
}
