import Link from "next/link";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { getInstitutionBySlug, getInstitutionProgrammes } from "@/lib/catalog";
import { Container } from "@/components/ui/Container";
import { ProgrammeCard } from "@/components/ProgrammeCard";
import { Checklist } from "@/components/ui/Checklist";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const institution = getInstitutionBySlug((await params).slug); return { title: institution?.name ?? "Institution", description: institution?.about ?? "Institution profile" }; }
export function generateStaticParams() { return [{ slug: "federal-university-of-enugu" }, { slug: "lagos-institute-of-technology" }]; }
export default async function InstitutionDetail({ params }: { params: Promise<{ slug: string }> }) {
  const institution = getInstitutionBySlug((await params).slug); if (!institution) notFound(); const programmes = getInstitutionProgrammes(institution.id);
  return <><div className="bg-navy-900 py-14 text-white"><Container><Link href="/institutions" className="text-sm text-white/65 hover:text-white">← All institutions</Link><div className="mt-9 flex items-center gap-5"><span className="flex size-16 items-center justify-center rounded-lg bg-white text-sm font-bold text-navy-800">{institution.shortName}</span><div><p className="text-sm text-teal-400">{institution.country}</p><h1 className="mt-1 text-3xl font-bold text-white md:text-5xl">{institution.name}</h1><p className="mt-3 flex items-center gap-2 text-sm text-white/70"><ShieldCheck size={16} className="text-teal-400" />{institution.accreditationStatus} · {institution.accreditationBody}</p></div></div></Container></div><Container><div className="grid gap-12 py-14 lg:grid-cols-[1fr_320px]"><main><section><h2 className="text-2xl font-bold text-navy-800">About {institution.shortName}</h2><p className="mt-4 max-w-2xl leading-7 text-ink-600">{institution.about}</p></section><section className="mt-14"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold text-navy-800">Programmes</h2><span className="text-sm text-ink-400">{programmes.length} listed</span></div><div className="mt-5 grid gap-4 md:grid-cols-2">{programmes.map((programme) => <ProgrammeCard key={programme.id} programme={programme} />)}</div></section><section className="mt-14"><h2 className="text-2xl font-bold text-navy-800">Academic policies</h2><div className="mt-5"><Checklist items={["Academic standards and assessment remain under institutional governance.", "Programme information and entry requirements are maintained by the institution.", "Credentials are issued by the institution and may be verified through Edulage when available."]} /></div></section></main><aside className="h-fit rounded-lg border border-line bg-surface p-6 lg:sticky lg:top-28"><h2 className="font-bold text-navy-800">Admissions</h2><p className="mt-3 text-sm leading-6 text-ink-600">Apply directly through the institution’s admissions portal. Edulage does not admit students.</p><a href={institution.admissionsPortalUrl} target="_blank" rel="noreferrer" className="mt-6 flex items-center justify-center gap-2 rounded-md bg-navy-800 px-4 py-3 text-sm font-semibold text-white hover:bg-navy-700">Visit admissions portal <ArrowRight size={16} /></a></aside></div></Container></>;
}
