import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Atom, Award, BrainCircuit, BriefcaseBusiness, CircleCheck, Cog, GraduationCap, HeartPulse, Landmark, Leaf, Monitor, Palette, Scale, ShieldCheck, Sprout, Users } from "lucide-react";
import { getDisciplineCounts, getFeaturedProgrammes, getInstitutions, getMarketplaceStats } from "@/lib/catalog";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { Button } from "@/components/ui/Button";
import { Checklist } from "@/components/ui/Checklist";
import { ProgrammeCard } from "@/components/ProgrammeCard";
import { SearchPanel } from "@/components/SearchPanel";

const iconMap: Record<string, typeof BriefcaseBusiness> = { BriefcaseBusiness, Monitor, Cog, HeartPulse, GraduationCap, Scale, Sprout, Users, Atom, Palette, Landmark, BrainCircuit, Leaf };
const featured = getFeaturedProgrammes(6);
const institutions = getInstitutions();
const disciplines = getDisciplineCounts();
const stats = getMarketplaceStats();

export default function Home() {
  return <div>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Organization", name: "Edulage", url: "https://edulage.org", description: "Global education infrastructure connecting learners with accredited institutions." }) }} />
    <section className="relative isolate overflow-hidden bg-navy-900 text-white"><Image src="/media/hero-lecture.jpg" alt="" fill priority sizes="100vw" className="absolute inset-0 -z-20 object-cover" /><div className="hero-media-overlay absolute inset-0 -z-10" /><div className="hero-grid absolute inset-0 -z-10 opacity-40" />
      <Container><div className="relative py-20 md:py-28"><p className="mb-5 text-xs font-bold uppercase tracking-[0.18em] text-teal-400">The global education exchange</p><h1 className="max-w-3xl text-4xl font-bold leading-tight text-white md:text-[56px]">Quality open and online education from accredited institutions worldwide.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">Discover degree and professional programmes from accredited universities, study fully online or at an accredited Open Education Center near you.</p><div className="mt-10 max-w-6xl"><SearchPanel /></div>
        <div className="mt-16 grid grid-cols-2 border-t border-white/20 pt-7 md:grid-cols-4">{[[String(stats.institutions), "Participating institutions"], [String(stats.programmes), "Programmes"], [String(stats.countries), "Countries represented"], [String(stats.centers), "Accredited Open Education Centers"]].map(([value, label]) => <div key={label} className="border-r border-white/15 px-4 py-2 first:pl-0 last:border-0 md:px-6"><p className="tabular-nums text-2xl font-bold text-teal-400">{value}</p><p className="mt-1 text-xs leading-5 text-white/60">{label}</p></div>)}</div>
      </div></Container>
    </section>
    <section className="border-b border-line bg-white py-7"><Container><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-ink-400">Institutions across the world</p><Link href="/institutions" className="arrow-slide flex shrink-0 items-center gap-1 text-xs font-semibold text-navy-800 hover:text-teal-600">View all institutions <span aria-hidden>→</span></Link></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{institutions.slice(0, 8).map((institution) => <Link key={institution.id} href={`/institutions/${institution.slug}`} className="group card-hover flex min-w-0 items-center gap-2 rounded-md border border-line px-2 py-2 focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2"><span className="flex h-10 w-14 shrink-0 items-center justify-center rounded-md bg-white p-1"><Image src={institution.logo} alt="" width={56} height={40} className="logo-muted size-full object-contain" /></span><span className="whitespace-nowrap text-xs font-semibold text-navy-800">{institution.shortName}</span></Link>)}</div></Container></section>
    <Section eyebrow="A clear path to study" title="How Edulage works" description="Edulage helps you find the right programme. The institution remains responsible for admissions, teaching, assessment, and credentials."><div className="grid gap-4 md:grid-cols-4">{[["01", "Discover", "Compare accredited programmes from institutions worldwide."], ["02", "Apply to the institution", "Applications are submitted and decided on the university’s own admission portal.", "Edulage does not process admissions."], ["03", "Learn online or at a center", "Study fully online, or use an accredited Open Education Center for devices, connectivity, and support."], ["04", "Earn an institution-issued credential", "Degrees and certificates are awarded by the university and verifiable on Edulage."]].map(([number, title, text, note]) => <div key={number} className="card-hover relative rounded-xl border border-line bg-white p-6 md:border-l-4 md:border-t-0"><span className="text-xs font-bold tracking-wider text-teal-600">{number}</span><h3 className="mt-3 text-lg font-bold text-navy-800">{title}</h3><p className="mt-2 text-sm leading-6 text-ink-600">{text}</p>{note && <p className="mt-3 text-xs font-semibold text-teal-600">{note}</p>}</div>)}</div></Section>
    <Section className="bg-surface" eyebrow="Find your field" title="Browse by discipline" description="Explore fields of study represented by institutions across regions, academic traditions, and professional contexts."><div className="grid grid-cols-2 gap-4 lg:grid-cols-3">{disciplines.map(({ name, count, icon, image }) => { const Icon = iconMap[icon]; return <Link href={`/programmes?discipline=${encodeURIComponent(name)}`} key={name} className="group relative aspect-[4/3] overflow-hidden rounded-xl bg-navy-800 text-white ring-1 ring-navy-900/10"><Image src={image} alt="" fill sizes="(max-width: 767px) 50vw, (max-width: 1279px) 33vw, 420px" className="image-zoom object-cover" /><div className="discipline-scrim absolute inset-0 transition-opacity duration-300 group-hover:opacity-95" /><div className="absolute inset-x-0 bottom-0 p-5"><span className="glass-chip inline-flex size-9 items-center justify-center rounded-lg"><Icon size={19} strokeWidth={1.8} /></span><h3 className="mt-3 text-base font-semibold">{name}</h3><p className="mt-1 text-xs text-white/80">{count} {count === 1 ? "programme" : "programmes"}</p></div><span className="absolute bottom-0 left-0 h-1 w-0 bg-teal-400 transition-[width] duration-300 group-hover:w-16" /></Link>; })}</div></Section>
    <Section eyebrow="Selected programmes" title="Study with an accredited institution"><div className="mb-8 flex items-center justify-between"><p className="max-w-lg text-sm text-ink-600">Explore a representative selection from the Edulage catalogue.</p><Link href="/programmes" className="flex items-center gap-2 text-sm font-semibold text-navy-800 hover:text-teal-600">View all programmes <ArrowRight size={16} /></Link></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{featured.map((programme) => <ProgrammeCard key={programme.id} programme={programme} />)}</div></Section>
    <Section className="bg-surface" eyebrow="A shared marketplace" title="Institutions on Edulage" description="Every accredited institution participates as a first-class tenant — there is no curated elite tier."><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{institutions.map((institution) => <Link href={`/institutions/${institution.slug}`} key={institution.id} className="group card-hover flex min-h-36 flex-col justify-between rounded-lg border border-line bg-white p-4 focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2"><span className="flex h-10 w-14 items-center justify-center overflow-hidden rounded-md border border-line bg-white p-1"><Image src={institution.logo} alt={`${institution.shortName} mark`} width={48} height={34} className="logo-muted size-full object-contain" /></span><span><span className="block text-sm font-semibold leading-5 text-navy-800">{institution.name}</span><span className="mt-1 block text-xs text-ink-400">{institution.city}, {institution.country}</span></span></Link>)}</div><Link href="/institutions" className="arrow-slide mt-8 inline-flex items-center gap-2 text-sm font-semibold text-navy-800 hover:text-teal-600">Explore all institutions <span aria-hidden>→</span></Link></Section>
    <section className="bg-surface pb-20 md:pb-28"><Container><div className="card-hover grid items-stretch gap-6 rounded-xl border border-line bg-white p-5 md:grid-cols-2 md:p-8"><div className="group relative min-h-[280px] overflow-hidden rounded-xl"><Image src="/media/oec-lab.jpg" alt="Learners working in an Open Education Center" fill sizes="(max-width: 767px) 100vw, 50vw" className="image-zoom object-cover" /><div className="image-scrim absolute inset-0" /><div className="absolute bottom-5 left-5 text-white"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-teal-400">Open Education Centers</p><p className="mt-2 text-xl font-bold">A reliable place to participate</p></div></div><div className="p-2 md:p-5"><h2 className="text-3xl font-bold text-navy-800">Study and sit your exams at an accredited center near you</h2><p className="mt-4 leading-7 text-ink-600">Open Education Centers provide internet-connected devices, structured study space, learner support, and secure CBT facilities for institution-required examinations.</p><div className="mt-6"><Checklist items={["Connected devices and reliable internet", "Structured study space", "Learner support", "Secure computer-based testing facilities"]} /></div><div className="mt-8 flex flex-wrap gap-3"><Button href="/open-education-centers">Find a center</Button><Button href="/open-education-centers" variant="secondary">Operate a center</Button></div></div></div></Container></section>
    <section className="border-b border-line bg-white py-20 md:py-24"><Container><div className="grid gap-10 md:grid-cols-[1fr_1.15fr] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-600">For institutions</p><h2 className="mt-3 text-3xl font-bold text-navy-800">Publish world-class courses without a studio.</h2><p className="mt-4 leading-7 text-ink-600">Edulage’s AI-assisted production tools help institutions structure curricula, develop materials and assessments, produce instructional video, and localize across languages — with all academic content remaining institution-owned and faculty-approved.</p><Link href="/for-institutions" className="arrow-slide mt-7 inline-flex items-center gap-2 text-sm font-semibold text-navy-800 hover:text-teal-600">Explore institutional tools <span aria-hidden>→</span></Link></div><div className="group relative min-h-[300px] overflow-hidden rounded-xl"><Image src="/media/ai-studio.jpg" alt="Instructional production studio" fill sizes="(max-width: 767px) 100vw, 50vw" className="image-zoom object-cover" /><div className="image-scrim absolute inset-0" /><div className="absolute bottom-5 left-5 text-white"><p className="font-semibold">Institution-owned and faculty-approved</p><p className="mt-1 text-sm text-white/75">A production layer around academic authority.</p></div></div></div></Container></section>
    <section className="border-b border-line bg-white"><Container><div className="grid divide-y divide-line md:grid-cols-3 md:divide-x md:divide-y-0">{[["Institution-controlled admissions", "Universities decide who they admit. Always.", ShieldCheck], ["Standards-based participation", "Institutions must meet and maintain digital readiness and academic governance requirements.", Award], ["Institution-issued credentials", "Edulage never awards qualifications; it makes them verifiable.", CircleCheck]].map(([title, text, Icon]) => <div key={title as string} className="flex gap-4 py-8 first:md:pr-8 md:px-8 md:first:pl-0 md:last:pr-0"><Icon className="shrink-0 text-teal-600" size={25} strokeWidth={1.5} /><div><h3 className="font-bold text-navy-800">{title as string}</h3><p className="mt-2 text-sm leading-6 text-ink-600">{text as string}</p></div></div>)}</div></Container></section>
    <section className="bg-navy-800 py-20 text-white md:py-24"><Container><div className="grid gap-12 md:grid-cols-[1.1fr_0.9fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-400">For institutions</p><h2 className="mt-3 text-3xl font-bold text-white md:text-4xl">Bring your institution online — globally.</h2><p className="mt-5 max-w-xl leading-7 text-white/75">Join shared infrastructure for global visibility and AI-enabled production while preserving academic sovereignty.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/for-institutions" variant="secondary">Apply to join Edulage</Button><Button href="/for-institutions" variant="ghost">Read the readiness requirements</Button></div></div><div><h3 className="mb-5 text-sm font-semibold text-white">Readiness requirements</h3><Checklist light items={["Digital admissions system", "Institutional management portal", "Automated result management", "Digital certification and transcripts", "Academic governance and quality assurance"]} /></div></div></Container></section>
    <section className="bg-surface py-8"><Container><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><p className="max-w-4xl text-sm leading-6 text-ink-600">Edulage is activated through the Global Open Education (GOE) Initiative — supporting institutional readiness, deploying Open Education Centers, and driving country-level adoption.</p><Link href="/goe" className="arrow-slide flex shrink-0 items-center gap-2 text-sm font-semibold text-navy-800 hover:text-teal-600">Learn about GOE <span aria-hidden>→</span></Link></div></Container></section>
    <section className="border-b border-line bg-white py-12"><Container><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold text-navy-800">Verify an Edulage-hosted credential</h2><p className="mt-1 text-sm text-ink-600">Verification launches with the first credential-issuing cohort.</p></div><form action="/verify" className="flex w-full max-w-md gap-2"><label htmlFor="credential-id" className="sr-only">Enter credential ID</label><input id="credential-id" name="id" placeholder="Enter credential ID" className="min-w-0 flex-1 rounded-md border border-line px-4 py-2.5 text-sm focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20" /><Button type="submit">Verify</Button></form></div></Container></section>
    <section className="border-b border-line bg-white py-12"><Container><div className="grid gap-6 md:grid-cols-[1.1fr_0.9fr] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-600">Verification infrastructure</p><h2 className="mt-2 text-xl font-bold text-navy-800">Credentials remain the institution’s responsibility</h2><p className="mt-2 text-sm leading-6 text-ink-600">Edulage provides a verification layer for records issued by participating institutions. No credential is awarded by Edulage.</p></div><div className="group relative h-40 overflow-hidden rounded-xl"><Image src="/media/credential.jpg" alt="Academic credential document" fill sizes="(max-width: 767px) 100vw, 40vw" className="image-zoom object-cover" /></div></div></Container></section>
  </div>;
}

export const metadata = { title: "Global education infrastructure", description: "Discover degree and professional programmes from accredited institutions worldwide." };
