import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Award, Building2, CheckCircle2, Globe2, GraduationCap, Landmark, Laptop2, MapPin, Network, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Container } from "@/components/ui/Container";
import { Button } from "@/components/ui/Button";
import { Checklist } from "@/components/ui/Checklist";

const audiences = [
  { icon: GraduationCap, title: "Learners", text: "Discover trusted pathways and participate online or through an accredited Open Education Center.", href: "/programmes", action: "Explore learning pathways" },
  { icon: Landmark, title: "Institutions", text: "Extend access, strengthen digital delivery and reach new learners while retaining full academic authority.", href: "/for-institutions", action: "Join the ecosystem" },
  { icon: Building2, title: "OEC operators", text: "Operate trusted local infrastructure for connectivity, learner support and secure assessment.", href: "/open-education-centers", action: "Explore OEC opportunities" },
  { icon: Globe2, title: "Governments & partners", text: "Build national readiness and expand equitable participation through the Global Open Education Initiative.", href: "/goe", action: "Partner through GOE" },
];

const journey = [
  [Search, "Discover", "Compare suitable programmes, delivery modes and participation requirements."],
  [Landmark, "Apply", "Submit your application directly to the institution that owns and delivers the programme."],
  [Laptop2, "Participate", "Learn online, with the option of local support and facilities through an accredited OEC."],
  [Award, "Earn", "Complete the institution’s assessment and receive an institution-issued credential."],
] as const;

export default function Home() {
  return (
    <main>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Organization", name: "EduLage", url: "https://edulage.org", slogan: "The Global Education Village", description: "Global education infrastructure connecting learners to quality open and online education from tertiary institutions worldwide." }) }} />

      <section className="hero-premium relative isolate overflow-hidden bg-navy-900 text-white">
        <div className="hero-grid absolute inset-0 -z-20 opacity-25" /><div className="hero-aurora absolute inset-0 -z-20" />
        <Container><div className="grid min-h-[720px] items-center gap-14 py-20 lg:grid-cols-[1.08fr_0.92fr] lg:py-24">
          <div className="relative z-10 max-w-3xl">
            <p className="flex items-center gap-3 text-xs font-bold uppercase tracking-[0.2em] text-teal-400"><span className="h-px w-8 bg-teal-400" /> The Global Education Village</p>
            <h1 className="mt-7 max-w-3xl text-[2.75rem] font-bold leading-[1.03] text-white sm:text-6xl lg:text-[4.35rem]">Quality education, connected to every community.</h1>
            <p className="mt-7 max-w-2xl text-lg leading-8 text-white/75 sm:text-xl">EduLage is shared global infrastructure connecting learners to quality open and online education from tertiary institutions worldwide—supported by trusted local access where it matters most.</p>
            <div className="mt-10 flex flex-wrap gap-3"><Button href="/programmes" variant="teal">Explore opportunities</Button><Button href="/for-institutions" variant="ghost">For institutions</Button></div>
            <div className="mt-10 grid max-w-2xl gap-4 border-t border-white/15 pt-6 sm:grid-cols-3">
              {[[ShieldCheck,"Institution-led","Academic authority protected"],[Network,"Globally connected","Shared digital infrastructure"],[MapPin,"Locally accessible","Support through accredited OECs"]].map(([Icon,title,text]) => <div key={title as string} className="flex gap-3"><Icon className="mt-0.5 shrink-0 text-teal-400" size={19}/><div><p className="text-sm font-semibold text-white">{title as string}</p><p className="mt-1 text-xs leading-5 text-white/55">{text as string}</p></div></div>)}
            </div>
          </div>
          <div className="relative mx-auto w-full max-w-[520px] lg:mx-0">
            <div className="hero-portrait relative aspect-[4/5] overflow-hidden rounded-[2rem] border border-white/15 shadow-2xl"><Image src="/media/hero-learner.jpg" alt="Learner participating in online education" fill priority sizes="(max-width: 1023px) 90vw, 42vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-navy-900/65 via-transparent to-transparent"/><div className="absolute inset-x-6 bottom-6 rounded-2xl border border-white/15 bg-navy-900/70 p-5 backdrop-blur-md"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-400">One connected ecosystem</p><p className="mt-2 text-lg font-semibold text-white">Institutions. Learners. Communities.</p></div></div>
            <div className="absolute -left-8 top-12 hidden rounded-2xl border border-white/15 bg-white p-4 text-navy-800 shadow-2xl md:block"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-teal-500/10"><GraduationCap size={20} className="text-teal-600"/></span><div><p className="text-xs text-ink-600">Academic ownership</p><p className="text-sm font-bold">Remains institutional</p></div></div></div>
            <div className="absolute -bottom-7 -right-5 hidden w-56 overflow-hidden rounded-2xl border-4 border-navy-900 bg-white shadow-2xl sm:block"><div className="relative h-28"><Image src="/media/hero-center-inset.jpg" alt="Open Education Center learning environment" fill sizes="224px" className="object-cover"/></div><div className="p-3"><p className="text-xs font-bold text-navy-800">Open Education Center</p><p className="mt-1 text-[11px] text-ink-600">Trusted local participation</p></div></div>
          </div>
        </div></Container>
      </section>

      <section className="border-b border-line bg-white py-9"><Container><div className="grid gap-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-bold text-navy-800">EduLage does not replace universities—it enables them.</p><p className="mt-1 text-sm leading-6 text-ink-600">Participating institutions retain admissions, curricula, teaching, assessment, results and certification.</p></div><Link href="/about" className="arrow-slide inline-flex items-center gap-2 text-sm font-semibold text-teal-600">Understand the EduLage model <ArrowRight size={16}/></Link></div></Container></section>

      <section className="bg-surface py-20 md:py-28"><Container><div className="max-w-3xl"><p className="section-kicker">A village built for participation</p><h2 className="section-title">One ecosystem. Clear pathways for everyone.</h2><p className="section-lead">EduLage brings the essential actors in open and online tertiary education into a trusted, standards-based environment.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{audiences.map(({icon:Icon,title,text,href,action},index)=><Link key={title} href={href} className="audience-card group flex min-h-[300px] flex-col rounded-2xl border border-line bg-white p-6"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-xl bg-teal-500/10 text-teal-600"><Icon size={24}/></span><span className="text-xs font-bold tabular-nums text-ink-400">0{index+1}</span></div><h3 className="mt-8 text-xl font-bold text-navy-800">{title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-ink-600">{text}</p><span className="arrow-slide mt-7 inline-flex items-center gap-2 text-sm font-semibold text-navy-800">{action} <ArrowRight size={15}/></span></Link>)}</div></Container></section>

      <section className="overflow-hidden bg-white py-20 md:py-28"><Container><div className="grid gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
        <div className="relative min-h-[480px] overflow-hidden rounded-[2rem] bg-navy-900"><Image src="/media/study-online.jpg" alt="Learner participating in online higher education" fill sizes="(max-width: 1023px) 100vw, 45vw" className="object-cover opacity-90"/><div className="absolute inset-0 bg-gradient-to-t from-navy-900 via-navy-900/10 to-transparent"/><div className="absolute inset-x-7 bottom-7 rounded-2xl border border-white/15 bg-navy-900/75 p-6 text-white backdrop-blur-md"><Sparkles size={22} className="text-teal-400"/><p className="mt-4 text-xl font-bold">Global reach. Local participation.</p><p className="mt-2 text-sm leading-6 text-white/65">A digital layer for discovery and delivery, supported by physical access infrastructure.</p></div></div>
        <div><p className="section-kicker">How EduLage works</p><h2 className="section-title">A trusted pathway from discovery to credential.</h2><p className="section-lead">The experience is connected, but institutional responsibilities remain unmistakably clear at every stage.</p><ol className="mt-10 space-y-3">{journey.map(([Icon,title,text],index)=><li key={title} className="journey-row group grid grid-cols-[44px_1fr] gap-4 rounded-xl border border-line p-5"><span className="grid size-11 place-items-center rounded-full bg-navy-800 text-white"><Icon size={19}/></span><div><div className="flex items-baseline justify-between gap-3"><h3 className="font-bold text-navy-800">{title}</h3><span className="text-[11px] font-bold text-teal-600">STEP 0{index+1}</span></div><p className="mt-2 text-sm leading-6 text-ink-600">{text}</p></div></li>)}</ol></div>
      </div></Container></section>

      <section className="bg-navy-900 py-20 text-white md:py-28"><Container><div className="grid gap-12 lg:grid-cols-[1fr_1fr] lg:items-center">
        <div><p className="section-kicker text-teal-400">Open Education Centers</p><h2 className="mt-4 text-3xl font-bold leading-tight text-white md:text-5xl">Bringing dependable access closer to the learner.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/65">Independently operated, EduLage-accredited OECs provide suitable places for connectivity, study support and secure institution-required assessment.</p><div className="mt-8"><Checklist light items={["Reliable connectivity and connected devices","Structured spaces for learning","Trained local learner support","Secure computer-based assessment facilities"]}/></div><div className="mt-9 flex flex-wrap gap-3"><Button href="/open-education-centers" variant="teal">Find an OEC</Button><Button href="/open-education-centers" variant="ghost">Become an OEC operator</Button></div></div>
        <div className="grid gap-4 sm:grid-cols-2"><div className="relative min-h-[430px] overflow-hidden rounded-2xl sm:row-span-2"><Image src="/media/oec-lab.jpg" alt="Learners using connected facilities in an Open Education Center" fill sizes="(max-width: 639px) 100vw, 25vw" className="object-cover"/></div><div className="relative min-h-[205px] overflow-hidden rounded-2xl"><Image src="/media/oec-exam.jpg" alt="Secure computer-based assessment facility" fill sizes="(max-width: 639px) 100vw, 25vw" className="object-cover"/></div><div className="rounded-2xl border border-white/15 bg-white/5 p-6"><MapPin className="text-teal-400" size={25}/><h3 className="mt-5 text-lg font-bold text-white">Rooted in communities</h3><p className="mt-2 text-sm leading-6 text-white/60">Designed to make online participation practical without transferring academic authority away from institutions.</p></div></div>
      </div></Container></section>

      <section className="bg-surface py-20 md:py-28"><Container><div className="grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">
        <div><p className="section-kicker">Global Open Education Initiative</p><h2 className="section-title">Preparing institutions and countries for meaningful participation.</h2><p className="section-lead">GOE is EduLage’s ecosystem-activation instrument—building readiness, partnerships and enabling infrastructure before institutions and communities participate at scale.</p><blockquote className="mt-8 border-l-2 border-teal-500 pl-5 text-xl font-semibold leading-8 text-navy-800">“GOE prepares the ecosystem. EduLage operates the ecosystem.”</blockquote><div className="mt-9 flex flex-wrap gap-3"><Button href="/goe">Explore the GOE Initiative</Button><Button href="/goe" variant="secondary">Discuss a partnership</Button></div></div>
        <div className="grid gap-4 sm:grid-cols-2">{[[ShieldCheck,"Institutional readiness","Strengthening systems, governance and digital delivery."],[Network,"OEC development","Activating dependable local access infrastructure."],[Users,"Partner mobilisation","Aligning public, private and development actors."],[Globe2,"Country adoption","Supporting coordinated national participation."]].map(([Icon,title,text])=><div key={title as string} className="rounded-2xl border border-line bg-white p-6"><Icon size={24} className="text-teal-600"/><h3 className="mt-5 font-bold text-navy-800">{title as string}</h3><p className="mt-2 text-sm leading-6 text-ink-600">{text as string}</p></div>)}</div>
      </div></Container></section>

      <section className="bg-white py-20 md:py-28"><Container><div className="grid gap-14 lg:grid-cols-[0.95fr_1.05fr] lg:items-center">
        <div className="relative min-h-[460px] overflow-hidden rounded-[2rem]"><Image src="/media/ai-studio.jpg" alt="Institutional team developing digital learning content" fill sizes="(max-width: 1023px) 100vw, 45vw" className="object-cover"/><div className="image-scrim absolute inset-0"/><div className="absolute bottom-7 left-7 right-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-400">Institution-owned. Faculty-approved.</p><p className="mt-3 text-xl font-bold">Technology around academic authority—not in place of it.</p></div></div>
        <div><p className="section-kicker">For tertiary institutions</p><h2 className="section-title">Extend your institution’s reach without surrendering its identity.</h2><p className="section-lead">EduLage provides infrastructure for programme discovery, digital production, learner participation and credential verification while your institution remains responsible for every academic decision.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Institution-controlled admissions","Institution-owned curricula","Faculty-led teaching and assessment","Institution-issued credentials","AI-assisted course production","Global learner discovery"].map(item=><div key={item} className="flex items-center gap-3 rounded-xl border border-line px-4 py-3 text-sm font-semibold text-navy-800"><CheckCircle2 size={18} className="shrink-0 text-teal-600"/>{item}</div>)}</div><div className="mt-9"><Button href="/for-institutions">Explore institutional participation</Button></div></div>
      </div></Container></section>

      <section className="border-y border-line bg-surface py-14"><Container><div className="grid divide-y divide-line md:grid-cols-3 md:divide-x md:divide-y-0">{[[ShieldCheck,"Academic sovereignty","Institutions retain authority over admissions, curriculum, teaching and assessment."],[Award,"Institution-issued credentials","EduLage does not award degrees, diplomas or certificates."],[CheckCircle2,"Standards-based participation","Institutions and OECs participate through defined readiness and accreditation requirements."]].map(([Icon,title,text])=><div key={title as string} className="py-7 first:md:pr-9 md:px-9 md:first:pl-0 md:last:pr-0"><Icon size={25} className="text-teal-600"/><h3 className="mt-5 text-lg font-bold text-navy-800">{title as string}</h3><p className="mt-2 text-sm leading-6 text-ink-600">{text as string}</p></div>)}</div></Container></section>

      <section className="relative isolate overflow-hidden bg-navy-800 py-20 text-white md:py-24"><div className="hero-grid absolute inset-0 -z-10 opacity-20"/><Container><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="section-kicker text-teal-400">Build the Global Education Village</p><h2 className="mt-4 max-w-3xl text-3xl font-bold leading-tight text-white md:text-5xl">A stronger education ecosystem begins with connected institutions and accessible communities.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Whether you represent a tertiary institution, government, development partner or prospective OEC operator, there is a pathway to participate.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><Button href="/for-institutions" variant="teal">Start a conversation</Button><Button href="/about" variant="ghost">Learn about EduLage</Button></div></div></Container></section>
    </main>
  );
}

export const metadata = { title: "EduLage — The Global Education Village", description: "Connecting learners to quality open and online education from tertiary institutions worldwide." };
