import { PolicyPage } from "@/components/PolicyPage";
export const metadata = { title: "Terms of use", description: "The terms governing use of EduLage, the learning platform and related services." };
export default function Page() {
  return <PolicyPage eyebrow="Legal" title="Terms of use" updated="7 October 2026" description="These terms govern your use of edulage.org, the EduLage learning platform, Studio and related services. By creating an account or using the services you agree to them." sections={[
    { title: "Who we are and what EduLage does", body: ["EduLage (“EduLage”, “we”, “us”) operates a global open-education platform that lets learners discover, enrol in and study programmes offered by participating tertiary institutions and training organisations (“institutions”), supported by a network of Global Open Education Centers (GOE Centers).", "EduLage is not itself an awarding institution. Every programme, admission decision, assessment, grade and credential belongs to the institution named on it. We provide the discovery, access, payment and learning-platform infrastructure through which institutions deliver their programmes."] },
    { title: "Your account", body: ["You may create one personal account. You must provide accurate information, keep your password confidential and tell us promptly if you believe your account has been used without your permission. You are responsible for activity under your account.", "Learner accounts are open to anyone aged 16 or over. Institution-staff roles (course author, instructor, admissions officer, institution administrator) are granted administratively by your institution and may require multi-factor authentication."] },
    { title: "Programme information", body: "Institutions control the information shown about their programmes — content, entry requirements, fees, dates and credentials — and are responsible for its accuracy. Listings labelled “Sample” are illustrative and are not offers. Before you apply or pay, confirm the details with the institution, in particular accreditation and recognition of the award for your intended purpose." },
    { title: "Enrolment, applications and admissions", body: ["Open courses allow direct enrolment. Admission-based programmes require an application that the institution reviews; the institution's decision is final and is made under its own admissions policies. Admission activates your enrolment automatically, and a declined or withdrawn application removes any provisional access.", "Institutions may set academic, attendance and conduct requirements for their programmes, including supervised assessment at a GOE Center."] },
    { title: "Fees and payments", body: "Where a fee applies it is shown before you enrol. Payments are processed by our payment provider (Paystack); EduLage does not store full card details. Receipts are e-mailed to you and available in My learning. Refunds are governed by our Refunds and payments policy and the institution's rules." },
    { title: "Acceptable use", body: "You agree not to misuse the services.", points: ["No impersonation or misrepresentation of identity, qualifications or affiliation", "No academic dishonesty, including plagiarism or sharing assessment answers", "No harassment, hate speech or unlawful, infringing or harmful content", "No interference with security, access controls or other users' accounts", "No automated scraping, bulk downloading or reselling of course content", "No use of the services for purposes unrelated to education and training"] },
    { title: "Content and intellectual property", body: ["Course materials belong to the institution or its licensors and are licensed to you for personal, non-commercial study while you are enrolled. The EduLage name, logo, website design and software are owned by EduLage.", "You retain ownership of work you submit, and grant the institution and EduLage the rights needed to assess, store and deliver it as part of the programme."] },
    { title: "Certificates and verification", body: "Certificates are issued by the institution and recorded on the learning platform. We provide a public verification service showing the learner name, award, institution, issue date and status. An institution may revoke a credential in accordance with its academic regulations, and the verification record will reflect this." },
    { title: "Suspension and termination", body: "We may suspend or close an account that breaches these terms, poses a security risk or is used for fraud. Institutions may remove learners from their programmes under their own regulations. You may close your account at any time by contacting us; academic records held by institutions are retained under their policies." },
    { title: "Availability and liability", body: ["We work to keep the services available and secure, but they are provided “as is”. We do not guarantee uninterrupted access, and planned maintenance will be announced where possible.", "To the extent permitted by law, EduLage is not liable for indirect or consequential loss, for the content or decisions of institutions, or for the recognition of any award by a third party. Nothing in these terms limits liability that cannot be limited by law."] },
    { title: "Changes and governing law", body: "We may update these terms; material changes are announced on the website or by e-mail and take effect no earlier than 14 days after notice. These terms are governed by the laws of the Federal Republic of Nigeria, and disputes are subject to the jurisdiction of its courts, without prejudice to mandatory consumer protections where you live." },
  ]} />;
}
