import Image from "next/image";
import Link from "next/link";
import { FileCheck2, GraduationCap, ShieldCheck } from "lucide-react";
import { PageIntro } from "@/components/PageIntro";
import { VerifyLookup } from "@/components/VerifyLookup";
import { Container } from "@/components/ui/Container";
export const metadata={title:"Verify a credential",description:"Check an institution-issued certificate or credential recorded through EduLage."};
const steps=[[GraduationCap,"Issued by the institution","Every credential is awarded by the named institution. EduLage records the issue; it never awards qualifications itself."],[FileCheck2,"Matched to the record","The ID on the certificate is checked against the institution's authorised record on the learning platform."],[ShieldCheck,"Status shown plainly","You see the learner, course or programme, institution and issue date, and whether the credential is valid or has been revoked."]] as const;
export default function Page(){return <><PageIntro eyebrow="Trust and records" title="Verify a credential" description="Employers, institutions and learners can confirm that a certificate recorded through EduLage is genuine — free, instantly and without creating an account."/>
<section className="py-16 md:py-20"><Container><div className="grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-start">
<div><VerifyLookup/><p className="mt-4 text-sm leading-6 text-ink-600">Certificates issued through EduLage carry a “Verify this credential” link of the form <code className="rounded bg-surface px-1.5 py-0.5 text-xs">edulage.org/verify/…</code>. Scanning the QR code on the certificate opens the same page.</p></div>
<div className="relative min-h-[300px] overflow-hidden rounded-2xl"><Image src="/media/credential.jpg" alt="Academic credential document" fill sizes="(max-width:1023px)100vw,40vw" className="object-cover"/><div className="image-scrim absolute inset-0"/><p className="absolute bottom-6 left-6 right-6 text-xl font-bold text-white">Credentials remain issued and owned by the awarding institution.</p></div>
</div></Container></section>
<section className="bg-surface py-16 md:py-20"><Container><p className="section-kicker">How verification works</p><h2 className="section-title">Three checks, one clear answer.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{steps.map(([Icon,title,text])=><div key={title} className="rounded-2xl border border-line bg-white p-6"><Icon className="text-teal-700"/><h3 className="mt-4 font-bold text-navy-800">{title}</h3><p className="mt-2 text-sm leading-6 text-ink-600">{text}</p></div>)}</div>
<div className="mt-10 grid gap-6 rounded-2xl bg-navy-900 p-7 text-white md:grid-cols-[1fr_auto] md:items-center"><div><h2 className="text-xl font-bold text-white">Verifying for an employer or another institution?</h2><p className="mt-2 max-w-3xl leading-7 text-white/70">A valid result confirms the record held on the learning platform. For transcripts, grades or recognition of the award for a specific purpose, contact the awarding institution directly — its details are shown with every result.</p></div><Link href="/quality-and-trust" className="rounded-xl bg-white px-6 py-3 text-sm font-bold text-navy-900">Quality and trust standards</Link></div></Container></section></>}
