import { PolicyPage } from "@/components/PolicyPage";
export const metadata = { title: "Data protection", description: "How responsibility for personal data is shared between EduLage, institutions and GOE Center operators, and how we keep it safe." };
export default function Page() {
  return <PolicyPage eyebrow="Trust and security" title="Data protection" updated="7 October 2026" description="EduLage, participating institutions and GOE Center operators each hold clearly defined responsibilities for the personal data of learners and staff. This page sets them out and explains the safeguards we apply." sections={[
    { title: "Shared responsibility", body: "Clear roles mean clear accountability.", points: ["EduLage: accounts, identity, platform operation, payments, support and the public verification record", "Institutions: applications, admissions, teaching records, grades, transcripts and credentials", "GOE Center operators: attendance, supervised-assessment and local-support records for learners they serve", "Learners and staff: keeping their credentials confidential and their profile accurate"] },
    { title: "Principles we follow", body: "Our processing follows the principles of the Nigeria Data Protection Act 2023, the NDPR and the GDPR where it applies: lawfulness and transparency, purpose limitation, data minimisation, accuracy, storage limitation, integrity and confidentiality, and accountability." },
    { title: "Technical safeguards", body: "", points: ["TLS encryption for every connection; HTTPS only", "Encrypted, access-controlled daily backups with regular restore rehearsals", "Single sign-in with multi-factor authentication for institution-staff roles", "Role-based access: staff see only their own institution's learners", "Audit logs of identity, role and admission events", "Uptime monitoring and alerting for every public service", "Payment card data handled solely by a PCI-DSS-certified provider"] },
    { title: "Organisational safeguards", body: "Access to personal data is limited to people who need it to do their job and is reviewed when roles change. Institution administrators are responsible for keeping their staff lists current. Suppliers who process data for us are bound by written contracts and processed only on our instructions." },
    { title: "Institution agreements", body: "Each participating institution signs a participation agreement that includes data-processing terms: the categories of data exchanged, the purposes, security obligations, breach notification within 72 hours and the handling of learner rights requests that concern both parties." },
    { title: "Breach response", body: "We maintain an incident-response runbook. If a breach is likely to affect your rights, we notify you and the Nigeria Data Protection Commission (or the relevant authority) without undue delay, explain what happened and what we are doing about it." },
    { title: "Exercising your rights", body: "Requests about account and platform data go to EduLage at support@edulage.org. Requests about academic records go to the institution concerned; if you are unsure, write to us and we will route the request and tell you who is handling it." },
  ]} />;
}
