import { PolicyPage } from "@/components/PolicyPage";
export const metadata = { title: "Privacy policy", description: "How EduLage collects, uses, shares and protects personal information." };
export default function Page() {
  return <PolicyPage eyebrow="Legal and privacy" title="Privacy policy" updated="7 October 2026" description="This policy explains what personal information EduLage collects when you use edulage.org, the learning platform and Studio, why we collect it, who we share it with and the rights you have." sections={[
    { title: "Who is responsible", body: "EduLage is the data controller for information collected on edulage.org and for the operation of the learning platform. Each participating institution is the controller for its own academic records — applications, admissions, grades and credentials — and processes them under its own privacy policy. GOE Center operators are controllers for the local-service records they hold." },
    { title: "Information we collect", body: "We collect only what is needed to provide the services.", points: ["Account details: name, e-mail address, password (stored hashed) and preferred language", "Profile information you choose to add, such as country and education background", "Applications, enrolments, progress, submissions and certificates", "Payment records: amount, reference and status (card details stay with the payment provider)", "Messages you send us and support interactions", "Technical data: IP address, device and browser type, pages visited and security logs"] },
    { title: "How we use it", body: "We use personal information to:", points: ["Create and secure your account and sign you in across EduLage services", "Deliver programmes, track progress and issue certificates", "Process applications and share them with the institution you applied to", "Take payments, issue receipts and prevent fraud", "Answer enquiries and provide learner support", "Send service e-mails about your account, enrolments and applications", "Improve the services and keep them available and secure", "Meet legal obligations, including tax and record-keeping"] },
    { title: "Legal bases", body: "We process personal information to perform our contract with you (providing the services), to meet legal obligations, with your consent where we ask for it (for example optional e-mails), and for our legitimate interests in securing and improving the services. Where the Nigeria Data Protection Act 2023 and the NDPR apply, we process in line with their principles of lawfulness, purpose limitation, data minimisation and accountability." },
    { title: "Who we share it with", body: ["Institutions you enrol with or apply to receive the information they need to admit, teach and certify you. GOE Centers you use receive the details needed to support you locally.", "Service providers act on our instructions under contract: cloud hosting (European Union data centres), identity and e-mail delivery, payment processing (Paystack) and website hosting. We do not sell personal information, and we share it with authorities only where the law requires."] },
    { title: "International transfers", body: "Our learning platform and identity services are hosted in the European Union; our website is served from a global content-delivery network. Where information moves between countries we rely on appropriate safeguards, including contractual protections, so that it remains protected to the standard described here." },
    { title: "How long we keep it", body: "Account information is kept while your account is active and for up to 24 months after it is closed, unless a longer period is required by law. Payment records are kept for seven years for tax purposes. Certificates and the verification record are kept for as long as the institution requires them to remain verifiable. Security logs are kept for up to 12 months." },
    { title: "Your rights", body: "You can exercise these rights by e-mailing support@edulage.org from your registered address or through the contact form.", points: ["Access the personal information we hold about you", "Correct inaccurate or incomplete information", "Delete your account and information, subject to legal retention", "Restrict or object to certain processing", "Receive your information in a portable format", "Withdraw consent at any time where processing is based on consent", "Lodge a complaint with the Nigeria Data Protection Commission or your local authority"] },
    { title: "Security", body: "We protect personal information with encryption in transit, encrypted backups, access controls, multi-factor authentication for staff roles, audit logging and regular restore testing. No system is perfectly secure; if a breach affects you we will notify you and the relevant authority as the law requires." },
    { title: "Children", body: "The services are intended for learners aged 16 and over. Institutions offering programmes to younger learners are responsible for obtaining appropriate parental consent and will tell you how they do so." },
    { title: "Cookies", body: "We use strictly necessary cookies to keep you signed in and protect against cross-site request forgery, and a small number of preference cookies. See our Cookie notice for details and how to control them." },
    { title: "Changes to this policy", body: "We will post any changes here with a new “last updated” date and, for material changes, tell you by e-mail or a notice on the website." },
  ]} />;
}
