import { PolicyPage } from "@/components/PolicyPage";
export const metadata = { title: "Accessibility", description: "EduLage's accessibility commitment, current conformance and how to get help or report a barrier." };
export default function Page() {
  return <PolicyPage eyebrow="Inclusive access" title="Accessibility at EduLage" updated="7 October 2026" description="Quality education should be reachable by everyone. We design edulage.org and the learning platform to work with assistive technologies, on any device and on slow connections, and we keep improving." sections={[
    { title: "Our commitment", body: "We aim to meet the Web Content Accessibility Guidelines (WCAG) 2.2 at level AA across edulage.org, the learning platform, Studio and our e-mails. Accessibility is part of our design reviews, our acceptance testing and the standards we ask institutions to follow for course content." },
    { title: "What you can expect", body: "", points: ["Full keyboard operation with visible focus indicators", "Meaningful headings, labels, link text and image descriptions", "Colour contrast of at least 4.5:1 for text and 3:1 for interface components", "Layouts that reflow on small screens and at 200% text size", "Captions on EduLage-produced video and transcripts on request", "Forms with clear instructions and specific error messages", "No content that flashes more than three times a second", "Compatibility with screen readers including NVDA, JAWS, VoiceOver and TalkBack"] },
    { title: "Known limitations", body: "Some course materials are created by institutions and may not yet meet every guideline — for example older PDFs without tags or third-party videos without captions. We help institutions remediate content and prioritise anything that blocks assessment. Supervised assessments at GOE Centers can be arranged with reasonable adjustments agreed with the institution." },
    { title: "Reasonable adjustments", body: "If you need extra time, an alternative format, assistive software or an accessible venue for a supervised assessment, tell the institution when you apply or enrol, or contact us and we will help you arrange it. Requests are handled confidentially." },
    { title: "Report a barrier", body: "If something on EduLage is hard to use, please tell us at support@edulage.org or through the contact form, choosing the topic “Something else” and describing the page and what happened. We acknowledge reports within two working days and aim to fix blocking issues within ten." },
    { title: "Assessment and review", body: "This statement is based on our own testing with automated tools and manual checks using keyboard and screen-reader navigation. We review it at least once a year and after every major redesign." },
  ]} />;
}
