import { Globe2, Landmark, Users } from "lucide-react";
import Image from "next/image";
import { PageIntro } from "@/components/PageIntro";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";

export const metadata = { title: "GOE Initiative", description: "The Global Open Education Initiative activates institutional readiness and access." };
export default function GoePage() {
  return <><PageIntro eyebrow="The enabling initiative" title="Global Open Education Initiative" description="GOE supports institutional readiness, deploys Open Education Centers, and drives country-level adoption of trusted open and online education." /><section className="group relative h-72 overflow-hidden bg-navy-900"><Image src="/media/goe-summit.jpg" alt="Education leaders collaborating at a global summit" fill sizes="100vw" className="image-zoom object-cover" /><div className="hero-media-overlay absolute inset-0" /><Container><div className="relative flex h-72 items-end pb-8 text-white"><p className="max-w-2xl text-2xl font-bold">Shared standards for a more connected world of higher education.</p></div></Container></section><Section title="Building the conditions for participation"><div className="grid gap-4 md:grid-cols-3">{[[Landmark, "Institutional readiness", "Support institutions to build the digital systems and governance required for responsible participation."], [Globe2, "Places to learn", "Deploy a network of accredited Open Education Centers that make online study practical and secure."], [Users, "Country adoption", "Work with public and institutional partners to establish durable country-level education infrastructure."]].map(([Icon, title, text]) => <div key={title as string} className="card-hover rounded-xl border border-line bg-white p-6"><Icon size={25} className="text-teal-600" /><h2 className="mt-5 font-bold text-navy-800">{title as string}</h2><p className="mt-3 text-sm leading-6 text-ink-600">{text as string}</p></div>)}</div></Section><section className="bg-navy-900 py-20 text-white"><Container><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-400">Global pilots</p><h2 className="mt-3 text-3xl font-bold text-white">A network designed for local conditions</h2><p className="mt-5 text-white/75 leading-7">GOE pilots bring together institutions, center operators, governments, and funders around a shared standard for digital access and academic trust.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{["Africa", "Asia Pacific", "Europe"].map((region) => <div key={region} className="card-hover rounded-xl border border-white/15 p-4 text-sm font-semibold text-white">{region}<span className="mt-2 block text-xs font-normal text-white/60">Regional network</span></div>)}</div></div></Container></section><section className="py-16 text-center"><h2 className="text-2xl font-bold text-navy-800">Learn how the network works</h2><a href="/about" className="arrow-slide mt-4 inline-flex items-center gap-2 text-sm font-semibold text-navy-800">About Edulage <span aria-hidden>→</span></a></section></>;
}
