import { MapPin, ShieldCheck, Wifi, Laptop, Users, MonitorCheck } from "lucide-react";
import { PageIntro } from "@/components/PageIntro";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { Button } from "@/components/ui/Button";
import { getCenters } from "@/lib/catalog";

export const metadata = { title: "Open Education Centers", description: "Find accredited Open Education Centers for connected study and secure examinations." };
export default function CentersPage() {
  const centers = getCenters();
  return <><PageIntro eyebrow="Access in place" title="Open Education Centers" description="Accredited Open Education Centers provide the devices, connectivity, study space, support, and secure facilities learners need to participate." /><Section title="Find a center" description="Static sample locations shown for this preview build."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{centers.map((center) => <article key={center.id} className="rounded-lg border border-line p-5"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-md bg-navy-800 text-white"><MapPin size={19} /></span><span className="flex items-center gap-1 text-xs font-semibold text-teal-600"><ShieldCheck size={14} />{center.status}</span></div><h2 className="mt-5 font-bold text-navy-800">{center.name}</h2><p className="mt-1 text-sm text-ink-400">{center.city}, {center.country}</p><ul className="mt-5 space-y-2">{center.facilities.map((facility) => <li key={facility} className="text-sm text-ink-600">· {facility}</li>)}</ul></article>)}</div></Section><section className="bg-surface py-20"><Container><div className="grid gap-10 md:grid-cols-2 md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-600">The center standard</p><h2 className="mt-3 text-3xl font-bold text-navy-800">A reliable place to participate</h2><p className="mt-4 leading-7 text-ink-600">Centers are assessed against standards for digital readiness, learner support, physical access, and secure computer-based testing.</p></div><div className="grid grid-cols-2 gap-3">{[[Wifi, "Reliable connectivity"], [Laptop, "Connected devices"], [Users, "Learner support"], [MonitorCheck, "Secure CBT"]].map(([Icon, label]) => <div key={label as string} className="rounded-lg border border-line bg-white p-5"><Icon size={22} className="text-teal-600" /><p className="mt-4 text-sm font-semibold text-navy-800">{label as string}</p></div>)}</div></div></Container></section><section className="py-16 text-center"><h2 className="text-2xl font-bold text-navy-800">Interested in operating a center?</h2><p className="mx-auto mt-3 max-w-xl text-ink-600">Review the operating standard and register your organization for assessment.</p><Button href="/for-institutions" className="mt-6">Operate a center</Button></section></>;
}
